/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 33
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 44
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_EQ = 2,
  anon_sym_struct = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_fun = 9,
  anon_sym_egg = 10,
  anon_sym_rock = 11,
  anon_sym_enum = 12,
  anon_sym_map = 13,
  anon_sym_type = 14,
  anon_sym_ayla = 15,
  anon_sym_elen = 16,
  anon_sym_four = 17,
  anon_sym_why = 18,
  anon_sym_back = 19,
  anon_sym_kitkat = 20,
  anon_sym_next = 21,
  anon_sym_decide = 22,
  anon_sym_when = 23,
  anon_sym_otherwise = 24,
  anon_sym_spawn = 25,
  anon_sym_with = 26,
  anon_sym_it = 27,
  anon_sym_in = 28,
  anon_sym_range = 29,
  anon_sym_int = 30,
  anon_sym_float = 31,
  anon_sym_string = 32,
  anon_sym_bool = 33,
  anon_sym_thing = 34,
  anon_sym_error = 35,
  anon_sym_DOT = 36,
  sym_type_identifier = 37,
  sym_number = 38,
  sym_string = 39,
  anon_sym_yes = 40,
  anon_sym_no = 41,
  sym_nil = 42,
  sym_comment = 43,
  sym_source_file = 44,
  sym__statement = 45,
  sym_assignment = 46,
  sym_struct_decl = 47,
  sym_struct_field = 48,
  sym_parameter_list = 49,
  sym_receiver = 50,
  sym_return_type = 51,
  sym_function_decl = 52,
  sym_block = 53,
  sym_keyword = 54,
  sym_primitive_type = 55,
  sym_expression = 56,
  sym_call_expression = 57,
  sym_member_expression = 58,
  sym_argument_list = 59,
  sym_boolean = 60,
  aux_sym_source_file_repeat1 = 61,
  aux_sym_struct_decl_repeat1 = 62,
  aux_sym_parameter_list_repeat1 = 63,
  aux_sym_argument_list_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_fun] = "fun",
  [anon_sym_egg] = "egg",
  [anon_sym_rock] = "rock",
  [anon_sym_enum] = "enum",
  [anon_sym_map] = "map",
  [anon_sym_type] = "type",
  [anon_sym_ayla] = "ayla",
  [anon_sym_elen] = "elen",
  [anon_sym_four] = "four",
  [anon_sym_why] = "why",
  [anon_sym_back] = "back",
  [anon_sym_kitkat] = "kitkat",
  [anon_sym_next] = "next",
  [anon_sym_decide] = "decide",
  [anon_sym_when] = "when",
  [anon_sym_otherwise] = "otherwise",
  [anon_sym_spawn] = "spawn",
  [anon_sym_with] = "with",
  [anon_sym_it] = "it",
  [anon_sym_in] = "in",
  [anon_sym_range] = "range",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_string] = "string",
  [anon_sym_bool] = "bool",
  [anon_sym_thing] = "thing",
  [anon_sym_error] = "error",
  [anon_sym_DOT] = ".",
  [sym_type_identifier] = "type_identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [sym_nil] = "nil",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_assignment] = "assignment",
  [sym_struct_decl] = "struct_decl",
  [sym_struct_field] = "struct_field",
  [sym_parameter_list] = "parameter_list",
  [sym_receiver] = "receiver",
  [sym_return_type] = "return_type",
  [sym_function_decl] = "function_decl",
  [sym_block] = "block",
  [sym_keyword] = "keyword",
  [sym_primitive_type] = "primitive_type",
  [sym_expression] = "expression",
  [sym_call_expression] = "call_expression",
  [sym_member_expression] = "member_expression",
  [sym_argument_list] = "argument_list",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_decl_repeat1] = "struct_decl_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_egg] = anon_sym_egg,
  [anon_sym_rock] = anon_sym_rock,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_ayla] = anon_sym_ayla,
  [anon_sym_elen] = anon_sym_elen,
  [anon_sym_four] = anon_sym_four,
  [anon_sym_why] = anon_sym_why,
  [anon_sym_back] = anon_sym_back,
  [anon_sym_kitkat] = anon_sym_kitkat,
  [anon_sym_next] = anon_sym_next,
  [anon_sym_decide] = anon_sym_decide,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_otherwise] = anon_sym_otherwise,
  [anon_sym_spawn] = anon_sym_spawn,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_it] = anon_sym_it,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_range] = anon_sym_range,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_thing] = anon_sym_thing,
  [anon_sym_error] = anon_sym_error,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_type_identifier] = sym_type_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [sym_nil] = sym_nil,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_assignment] = sym_assignment,
  [sym_struct_decl] = sym_struct_decl,
  [sym_struct_field] = sym_struct_field,
  [sym_parameter_list] = sym_parameter_list,
  [sym_receiver] = sym_receiver,
  [sym_return_type] = sym_return_type,
  [sym_function_decl] = sym_function_decl,
  [sym_block] = sym_block,
  [sym_keyword] = sym_keyword,
  [sym_primitive_type] = sym_primitive_type,
  [sym_expression] = sym_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_member_expression] = sym_member_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_decl_repeat1] = aux_sym_struct_decl_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_egg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ayla] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_four] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_why] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_back] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_kitkat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_next] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decide] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_otherwise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spawn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_it] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_thing] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_receiver] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_function = 1,
  field_keyword = 2,
  field_left = 3,
  field_name = 4,
  field_object = 5,
  field_property = 6,
  field_receiver = 7,
  field_return_type = 8,
  field_right = 9,
  field_type = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_keyword] = "keyword",
  [field_left] = "left",
  [field_name] = "name",
  [field_object] = "object",
  [field_property] = "property",
  [field_receiver] = "receiver",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 1},
  [11] = {.index = 17, .length = 2},
  [12] = {.index = 19, .length = 3},
  [13] = {.index = 22, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_right, 2},
  [2] =
    {field_function, 0},
  [3] =
    {field_object, 0},
    {field_property, 2},
  [5] =
    {field_keyword, 0},
    {field_name, 1},
  [7] =
    {field_name, 0},
    {field_type, 1},
  [9] =
    {field_name, 1},
    {field_type, 2},
  [11] =
    {field_name, 1},
  [12] =
    {field_name, 1},
    {field_return_type, 4},
  [14] =
    {field_name, 2},
    {field_receiver, 1},
  [16] =
    {field_type, 1},
  [17] =
    {field_name, 1},
    {field_return_type, 5},
  [19] =
    {field_name, 2},
    {field_receiver, 1},
    {field_return_type, 5},
  [22] =
    {field_name, 2},
    {field_receiver, 1},
    {field_return_type, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 1,
        '(', 10,
        ')', 11,
        ',', 9,
        '.', 12,
        '/', 2,
        '=', 6,
        '{', 7,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'd', 3,
        'e', 4,
        'f', 5,
        'i', 6,
        'k', 7,
        'm', 8,
        'n', 9,
        'o', 10,
        'r', 11,
        's', 12,
        't', 13,
        'w', 14,
        'y', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(37);
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(39);
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_it);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'x') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_no);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 36:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(67);
      if (lookahead == 'y') ADVANCE(68);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 45:
      if (lookahead == 'k') ADVANCE(72);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_egg);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 50:
      if (lookahead == 'm') ADVANCE(76);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(77);
      END_STATE();
    case 52:
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 56:
      if (lookahead == 'k') ADVANCE(80);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'g') ADVANCE(83);
      END_STATE();
    case 62:
      if (lookahead == 'k') ADVANCE(84);
      END_STATE();
    case 63:
      if (lookahead == 'w') ADVANCE(85);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(86);
      if (lookahead == 'u') ADVANCE(87);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_why);
      END_STATE();
    case 69:
      if (lookahead == 'h') ADVANCE(91);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_yes);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_ayla);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_back);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 74:
      if (lookahead == 'd') ADVANCE(92);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_elen);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_four);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_next);
      END_STATE();
    case 82:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 83:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_rock);
      END_STATE();
    case 85:
      if (lookahead == 'n') ADVANCE(98);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 87:
      if (lookahead == 'c') ADVANCE(100);
      END_STATE();
    case 88:
      if (lookahead == 'g') ADVANCE(101);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 92:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_error);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 95:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 96:
      if (lookahead == 'w') ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_spawn);
      END_STATE();
    case 99:
      if (lookahead == 'g') ADVANCE(105);
      END_STATE();
    case 100:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_thing);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_decide);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_kitkat);
      END_STATE();
    case 104:
      if (lookahead == 'i') ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 107:
      if (lookahead == 's') ADVANCE(108);
      END_STATE();
    case 108:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_otherwise);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_egg] = ACTIONS(1),
    [anon_sym_rock] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_ayla] = ACTIONS(1),
    [anon_sym_elen] = ACTIONS(1),
    [anon_sym_four] = ACTIONS(1),
    [anon_sym_why] = ACTIONS(1),
    [anon_sym_back] = ACTIONS(1),
    [anon_sym_kitkat] = ACTIONS(1),
    [anon_sym_next] = ACTIONS(1),
    [anon_sym_decide] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_otherwise] = ACTIONS(1),
    [anon_sym_spawn] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_it] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_thing] = ACTIONS(1),
    [anon_sym_error] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(68),
    [sym__statement] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_struct_decl] = STATE(3),
    [sym_function_decl] = STATE(3),
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(19),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_struct_decl] = STATE(2),
    [sym_function_decl] = STATE(2),
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(19),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_struct] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_fun] = ACTIONS(31),
    [anon_sym_egg] = ACTIONS(34),
    [anon_sym_rock] = ACTIONS(34),
    [anon_sym_enum] = ACTIONS(34),
    [anon_sym_map] = ACTIONS(34),
    [anon_sym_type] = ACTIONS(34),
    [anon_sym_ayla] = ACTIONS(34),
    [anon_sym_elen] = ACTIONS(34),
    [anon_sym_four] = ACTIONS(34),
    [anon_sym_why] = ACTIONS(34),
    [anon_sym_back] = ACTIONS(34),
    [anon_sym_kitkat] = ACTIONS(34),
    [anon_sym_next] = ACTIONS(34),
    [anon_sym_decide] = ACTIONS(34),
    [anon_sym_when] = ACTIONS(34),
    [anon_sym_otherwise] = ACTIONS(34),
    [anon_sym_spawn] = ACTIONS(34),
    [anon_sym_with] = ACTIONS(34),
    [anon_sym_it] = ACTIONS(34),
    [anon_sym_in] = ACTIONS(34),
    [anon_sym_range] = ACTIONS(34),
    [anon_sym_int] = ACTIONS(37),
    [anon_sym_float] = ACTIONS(37),
    [anon_sym_string] = ACTIONS(37),
    [anon_sym_bool] = ACTIONS(37),
    [anon_sym_thing] = ACTIONS(37),
    [anon_sym_error] = ACTIONS(37),
    [sym_number] = ACTIONS(40),
    [sym_string] = ACTIONS(40),
    [anon_sym_yes] = ACTIONS(43),
    [anon_sym_no] = ACTIONS(43),
    [sym_nil] = ACTIONS(46),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_struct_decl] = STATE(2),
    [sym_function_decl] = STATE(2),
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(19),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(5),
    [sym_assignment] = STATE(5),
    [sym_struct_decl] = STATE(5),
    [sym_function_decl] = STATE(5),
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(19),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_struct_decl] = STATE(2),
    [sym_function_decl] = STATE(2),
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(19),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(36),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_argument_list] = STATE(63),
    [sym_boolean] = STATE(11),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_struct] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_struct] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(61),
    [anon_sym_egg] = ACTIONS(61),
    [anon_sym_rock] = ACTIONS(61),
    [anon_sym_enum] = ACTIONS(61),
    [anon_sym_map] = ACTIONS(61),
    [anon_sym_type] = ACTIONS(61),
    [anon_sym_ayla] = ACTIONS(61),
    [anon_sym_elen] = ACTIONS(61),
    [anon_sym_four] = ACTIONS(61),
    [anon_sym_why] = ACTIONS(61),
    [anon_sym_back] = ACTIONS(61),
    [anon_sym_kitkat] = ACTIONS(61),
    [anon_sym_next] = ACTIONS(61),
    [anon_sym_decide] = ACTIONS(61),
    [anon_sym_when] = ACTIONS(61),
    [anon_sym_otherwise] = ACTIONS(61),
    [anon_sym_spawn] = ACTIONS(61),
    [anon_sym_with] = ACTIONS(61),
    [anon_sym_it] = ACTIONS(61),
    [anon_sym_in] = ACTIONS(61),
    [anon_sym_range] = ACTIONS(61),
    [anon_sym_int] = ACTIONS(61),
    [anon_sym_float] = ACTIONS(61),
    [anon_sym_string] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(61),
    [anon_sym_thing] = ACTIONS(61),
    [anon_sym_error] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_yes] = ACTIONS(61),
    [anon_sym_no] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [anon_sym_struct] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_fun] = ACTIONS(67),
    [anon_sym_egg] = ACTIONS(67),
    [anon_sym_rock] = ACTIONS(67),
    [anon_sym_enum] = ACTIONS(67),
    [anon_sym_map] = ACTIONS(67),
    [anon_sym_type] = ACTIONS(67),
    [anon_sym_ayla] = ACTIONS(67),
    [anon_sym_elen] = ACTIONS(67),
    [anon_sym_four] = ACTIONS(67),
    [anon_sym_why] = ACTIONS(67),
    [anon_sym_back] = ACTIONS(67),
    [anon_sym_kitkat] = ACTIONS(67),
    [anon_sym_next] = ACTIONS(67),
    [anon_sym_decide] = ACTIONS(67),
    [anon_sym_when] = ACTIONS(67),
    [anon_sym_otherwise] = ACTIONS(67),
    [anon_sym_spawn] = ACTIONS(67),
    [anon_sym_with] = ACTIONS(67),
    [anon_sym_it] = ACTIONS(67),
    [anon_sym_in] = ACTIONS(67),
    [anon_sym_range] = ACTIONS(67),
    [anon_sym_int] = ACTIONS(67),
    [anon_sym_float] = ACTIONS(67),
    [anon_sym_string] = ACTIONS(67),
    [anon_sym_bool] = ACTIONS(67),
    [anon_sym_thing] = ACTIONS(67),
    [anon_sym_error] = ACTIONS(67),
    [anon_sym_DOT] = ACTIONS(65),
    [sym_number] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_yes] = ACTIONS(67),
    [anon_sym_no] = ACTIONS(67),
    [sym_nil] = ACTIONS(67),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_struct] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_fun] = ACTIONS(71),
    [anon_sym_egg] = ACTIONS(71),
    [anon_sym_rock] = ACTIONS(71),
    [anon_sym_enum] = ACTIONS(71),
    [anon_sym_map] = ACTIONS(71),
    [anon_sym_type] = ACTIONS(71),
    [anon_sym_ayla] = ACTIONS(71),
    [anon_sym_elen] = ACTIONS(71),
    [anon_sym_four] = ACTIONS(71),
    [anon_sym_why] = ACTIONS(71),
    [anon_sym_back] = ACTIONS(71),
    [anon_sym_kitkat] = ACTIONS(71),
    [anon_sym_next] = ACTIONS(71),
    [anon_sym_decide] = ACTIONS(71),
    [anon_sym_when] = ACTIONS(71),
    [anon_sym_otherwise] = ACTIONS(71),
    [anon_sym_spawn] = ACTIONS(71),
    [anon_sym_with] = ACTIONS(71),
    [anon_sym_it] = ACTIONS(71),
    [anon_sym_in] = ACTIONS(71),
    [anon_sym_range] = ACTIONS(71),
    [anon_sym_int] = ACTIONS(71),
    [anon_sym_float] = ACTIONS(71),
    [anon_sym_string] = ACTIONS(71),
    [anon_sym_bool] = ACTIONS(71),
    [anon_sym_thing] = ACTIONS(71),
    [anon_sym_error] = ACTIONS(71),
    [anon_sym_DOT] = ACTIONS(69),
    [sym_number] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [anon_sym_yes] = ACTIONS(71),
    [anon_sym_no] = ACTIONS(71),
    [sym_nil] = ACTIONS(71),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_struct] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_fun] = ACTIONS(75),
    [anon_sym_egg] = ACTIONS(75),
    [anon_sym_rock] = ACTIONS(75),
    [anon_sym_enum] = ACTIONS(75),
    [anon_sym_map] = ACTIONS(75),
    [anon_sym_type] = ACTIONS(75),
    [anon_sym_ayla] = ACTIONS(75),
    [anon_sym_elen] = ACTIONS(75),
    [anon_sym_four] = ACTIONS(75),
    [anon_sym_why] = ACTIONS(75),
    [anon_sym_back] = ACTIONS(75),
    [anon_sym_kitkat] = ACTIONS(75),
    [anon_sym_next] = ACTIONS(75),
    [anon_sym_decide] = ACTIONS(75),
    [anon_sym_when] = ACTIONS(75),
    [anon_sym_otherwise] = ACTIONS(75),
    [anon_sym_spawn] = ACTIONS(75),
    [anon_sym_with] = ACTIONS(75),
    [anon_sym_it] = ACTIONS(75),
    [anon_sym_in] = ACTIONS(75),
    [anon_sym_range] = ACTIONS(75),
    [anon_sym_int] = ACTIONS(75),
    [anon_sym_float] = ACTIONS(75),
    [anon_sym_string] = ACTIONS(75),
    [anon_sym_bool] = ACTIONS(75),
    [anon_sym_thing] = ACTIONS(75),
    [anon_sym_error] = ACTIONS(75),
    [anon_sym_DOT] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [anon_sym_yes] = ACTIONS(75),
    [anon_sym_no] = ACTIONS(75),
    [sym_nil] = ACTIONS(75),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_struct] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(61),
    [anon_sym_egg] = ACTIONS(61),
    [anon_sym_rock] = ACTIONS(61),
    [anon_sym_enum] = ACTIONS(61),
    [anon_sym_map] = ACTIONS(61),
    [anon_sym_type] = ACTIONS(61),
    [anon_sym_ayla] = ACTIONS(61),
    [anon_sym_elen] = ACTIONS(61),
    [anon_sym_four] = ACTIONS(61),
    [anon_sym_why] = ACTIONS(61),
    [anon_sym_back] = ACTIONS(61),
    [anon_sym_kitkat] = ACTIONS(61),
    [anon_sym_next] = ACTIONS(61),
    [anon_sym_decide] = ACTIONS(61),
    [anon_sym_when] = ACTIONS(61),
    [anon_sym_otherwise] = ACTIONS(61),
    [anon_sym_spawn] = ACTIONS(61),
    [anon_sym_with] = ACTIONS(61),
    [anon_sym_it] = ACTIONS(61),
    [anon_sym_in] = ACTIONS(61),
    [anon_sym_range] = ACTIONS(61),
    [anon_sym_int] = ACTIONS(61),
    [anon_sym_float] = ACTIONS(61),
    [anon_sym_string] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(61),
    [anon_sym_thing] = ACTIONS(61),
    [anon_sym_error] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_yes] = ACTIONS(61),
    [anon_sym_no] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_struct] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_fun] = ACTIONS(61),
    [anon_sym_egg] = ACTIONS(61),
    [anon_sym_rock] = ACTIONS(61),
    [anon_sym_enum] = ACTIONS(61),
    [anon_sym_map] = ACTIONS(61),
    [anon_sym_type] = ACTIONS(61),
    [anon_sym_ayla] = ACTIONS(61),
    [anon_sym_elen] = ACTIONS(61),
    [anon_sym_four] = ACTIONS(61),
    [anon_sym_why] = ACTIONS(61),
    [anon_sym_back] = ACTIONS(61),
    [anon_sym_kitkat] = ACTIONS(61),
    [anon_sym_next] = ACTIONS(61),
    [anon_sym_decide] = ACTIONS(61),
    [anon_sym_when] = ACTIONS(61),
    [anon_sym_otherwise] = ACTIONS(61),
    [anon_sym_spawn] = ACTIONS(61),
    [anon_sym_with] = ACTIONS(61),
    [anon_sym_it] = ACTIONS(61),
    [anon_sym_in] = ACTIONS(61),
    [anon_sym_range] = ACTIONS(61),
    [anon_sym_int] = ACTIONS(61),
    [anon_sym_float] = ACTIONS(61),
    [anon_sym_string] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(61),
    [anon_sym_thing] = ACTIONS(61),
    [anon_sym_error] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_yes] = ACTIONS(61),
    [anon_sym_no] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(20),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_struct] = ACTIONS(13),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_identifier] = ACTIONS(81),
    [anon_sym_struct] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_fun] = ACTIONS(81),
    [anon_sym_egg] = ACTIONS(81),
    [anon_sym_rock] = ACTIONS(81),
    [anon_sym_enum] = ACTIONS(81),
    [anon_sym_map] = ACTIONS(81),
    [anon_sym_type] = ACTIONS(81),
    [anon_sym_ayla] = ACTIONS(81),
    [anon_sym_elen] = ACTIONS(81),
    [anon_sym_four] = ACTIONS(81),
    [anon_sym_why] = ACTIONS(81),
    [anon_sym_back] = ACTIONS(81),
    [anon_sym_kitkat] = ACTIONS(81),
    [anon_sym_next] = ACTIONS(81),
    [anon_sym_decide] = ACTIONS(81),
    [anon_sym_when] = ACTIONS(81),
    [anon_sym_otherwise] = ACTIONS(81),
    [anon_sym_spawn] = ACTIONS(81),
    [anon_sym_with] = ACTIONS(81),
    [anon_sym_it] = ACTIONS(81),
    [anon_sym_in] = ACTIONS(81),
    [anon_sym_range] = ACTIONS(81),
    [anon_sym_int] = ACTIONS(81),
    [anon_sym_float] = ACTIONS(81),
    [anon_sym_string] = ACTIONS(81),
    [anon_sym_bool] = ACTIONS(81),
    [anon_sym_thing] = ACTIONS(81),
    [anon_sym_error] = ACTIONS(81),
    [anon_sym_DOT] = ACTIONS(79),
    [sym_number] = ACTIONS(79),
    [sym_string] = ACTIONS(79),
    [anon_sym_yes] = ACTIONS(81),
    [anon_sym_no] = ACTIONS(81),
    [sym_nil] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_identifier] = ACTIONS(85),
    [anon_sym_struct] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(83),
    [anon_sym_COMMA] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_fun] = ACTIONS(85),
    [anon_sym_egg] = ACTIONS(85),
    [anon_sym_rock] = ACTIONS(85),
    [anon_sym_enum] = ACTIONS(85),
    [anon_sym_map] = ACTIONS(85),
    [anon_sym_type] = ACTIONS(85),
    [anon_sym_ayla] = ACTIONS(85),
    [anon_sym_elen] = ACTIONS(85),
    [anon_sym_four] = ACTIONS(85),
    [anon_sym_why] = ACTIONS(85),
    [anon_sym_back] = ACTIONS(85),
    [anon_sym_kitkat] = ACTIONS(85),
    [anon_sym_next] = ACTIONS(85),
    [anon_sym_decide] = ACTIONS(85),
    [anon_sym_when] = ACTIONS(85),
    [anon_sym_otherwise] = ACTIONS(85),
    [anon_sym_spawn] = ACTIONS(85),
    [anon_sym_with] = ACTIONS(85),
    [anon_sym_it] = ACTIONS(85),
    [anon_sym_in] = ACTIONS(85),
    [anon_sym_range] = ACTIONS(85),
    [anon_sym_int] = ACTIONS(85),
    [anon_sym_float] = ACTIONS(85),
    [anon_sym_string] = ACTIONS(85),
    [anon_sym_bool] = ACTIONS(85),
    [anon_sym_thing] = ACTIONS(85),
    [anon_sym_error] = ACTIONS(85),
    [anon_sym_DOT] = ACTIONS(83),
    [sym_number] = ACTIONS(83),
    [sym_string] = ACTIONS(83),
    [anon_sym_yes] = ACTIONS(85),
    [anon_sym_no] = ACTIONS(85),
    [sym_nil] = ACTIONS(85),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [sym_keyword] = STATE(11),
    [sym_primitive_type] = STATE(11),
    [sym_expression] = STATE(47),
    [sym_call_expression] = STATE(11),
    [sym_member_expression] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_struct] = ACTIONS(13),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(87),
    [sym_identifier] = ACTIONS(89),
    [anon_sym_struct] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_COMMA] = ACTIONS(87),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_fun] = ACTIONS(89),
    [anon_sym_egg] = ACTIONS(89),
    [anon_sym_rock] = ACTIONS(89),
    [anon_sym_enum] = ACTIONS(89),
    [anon_sym_map] = ACTIONS(89),
    [anon_sym_type] = ACTIONS(89),
    [anon_sym_ayla] = ACTIONS(89),
    [anon_sym_elen] = ACTIONS(89),
    [anon_sym_four] = ACTIONS(89),
    [anon_sym_why] = ACTIONS(89),
    [anon_sym_back] = ACTIONS(89),
    [anon_sym_kitkat] = ACTIONS(89),
    [anon_sym_next] = ACTIONS(89),
    [anon_sym_decide] = ACTIONS(89),
    [anon_sym_when] = ACTIONS(89),
    [anon_sym_otherwise] = ACTIONS(89),
    [anon_sym_spawn] = ACTIONS(89),
    [anon_sym_with] = ACTIONS(89),
    [anon_sym_it] = ACTIONS(89),
    [anon_sym_in] = ACTIONS(89),
    [anon_sym_range] = ACTIONS(89),
    [anon_sym_int] = ACTIONS(89),
    [anon_sym_float] = ACTIONS(89),
    [anon_sym_string] = ACTIONS(89),
    [anon_sym_bool] = ACTIONS(89),
    [anon_sym_thing] = ACTIONS(89),
    [anon_sym_error] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(87),
    [sym_number] = ACTIONS(87),
    [sym_string] = ACTIONS(87),
    [anon_sym_yes] = ACTIONS(89),
    [anon_sym_no] = ACTIONS(89),
    [sym_nil] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_struct] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_fun] = ACTIONS(75),
    [anon_sym_egg] = ACTIONS(75),
    [anon_sym_rock] = ACTIONS(75),
    [anon_sym_enum] = ACTIONS(75),
    [anon_sym_map] = ACTIONS(75),
    [anon_sym_type] = ACTIONS(75),
    [anon_sym_ayla] = ACTIONS(75),
    [anon_sym_elen] = ACTIONS(75),
    [anon_sym_four] = ACTIONS(75),
    [anon_sym_why] = ACTIONS(75),
    [anon_sym_back] = ACTIONS(75),
    [anon_sym_kitkat] = ACTIONS(75),
    [anon_sym_next] = ACTIONS(75),
    [anon_sym_decide] = ACTIONS(75),
    [anon_sym_when] = ACTIONS(75),
    [anon_sym_otherwise] = ACTIONS(75),
    [anon_sym_spawn] = ACTIONS(75),
    [anon_sym_with] = ACTIONS(75),
    [anon_sym_it] = ACTIONS(75),
    [anon_sym_in] = ACTIONS(75),
    [anon_sym_range] = ACTIONS(75),
    [anon_sym_int] = ACTIONS(75),
    [anon_sym_float] = ACTIONS(75),
    [anon_sym_string] = ACTIONS(75),
    [anon_sym_bool] = ACTIONS(75),
    [anon_sym_thing] = ACTIONS(75),
    [anon_sym_error] = ACTIONS(75),
    [anon_sym_DOT] = ACTIONS(73),
    [sym_type_identifier] = ACTIONS(91),
    [sym_number] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [anon_sym_yes] = ACTIONS(75),
    [anon_sym_no] = ACTIONS(75),
    [sym_nil] = ACTIONS(75),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_identifier] = ACTIONS(95),
    [anon_sym_struct] = ACTIONS(95),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_fun] = ACTIONS(95),
    [anon_sym_egg] = ACTIONS(95),
    [anon_sym_rock] = ACTIONS(95),
    [anon_sym_enum] = ACTIONS(95),
    [anon_sym_map] = ACTIONS(95),
    [anon_sym_type] = ACTIONS(95),
    [anon_sym_ayla] = ACTIONS(95),
    [anon_sym_elen] = ACTIONS(95),
    [anon_sym_four] = ACTIONS(95),
    [anon_sym_why] = ACTIONS(95),
    [anon_sym_back] = ACTIONS(95),
    [anon_sym_kitkat] = ACTIONS(95),
    [anon_sym_next] = ACTIONS(95),
    [anon_sym_decide] = ACTIONS(95),
    [anon_sym_when] = ACTIONS(95),
    [anon_sym_otherwise] = ACTIONS(95),
    [anon_sym_spawn] = ACTIONS(95),
    [anon_sym_with] = ACTIONS(95),
    [anon_sym_it] = ACTIONS(95),
    [anon_sym_in] = ACTIONS(95),
    [anon_sym_range] = ACTIONS(95),
    [anon_sym_int] = ACTIONS(95),
    [anon_sym_float] = ACTIONS(95),
    [anon_sym_string] = ACTIONS(95),
    [anon_sym_bool] = ACTIONS(95),
    [anon_sym_thing] = ACTIONS(95),
    [anon_sym_error] = ACTIONS(95),
    [anon_sym_DOT] = ACTIONS(97),
    [sym_number] = ACTIONS(93),
    [sym_string] = ACTIONS(93),
    [anon_sym_yes] = ACTIONS(95),
    [anon_sym_no] = ACTIONS(95),
    [sym_nil] = ACTIONS(95),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(99),
    [sym_identifier] = ACTIONS(101),
    [anon_sym_struct] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_fun] = ACTIONS(101),
    [anon_sym_egg] = ACTIONS(101),
    [anon_sym_rock] = ACTIONS(101),
    [anon_sym_enum] = ACTIONS(101),
    [anon_sym_map] = ACTIONS(101),
    [anon_sym_type] = ACTIONS(101),
    [anon_sym_ayla] = ACTIONS(101),
    [anon_sym_elen] = ACTIONS(101),
    [anon_sym_four] = ACTIONS(101),
    [anon_sym_why] = ACTIONS(101),
    [anon_sym_back] = ACTIONS(101),
    [anon_sym_kitkat] = ACTIONS(101),
    [anon_sym_next] = ACTIONS(101),
    [anon_sym_decide] = ACTIONS(101),
    [anon_sym_when] = ACTIONS(101),
    [anon_sym_otherwise] = ACTIONS(101),
    [anon_sym_spawn] = ACTIONS(101),
    [anon_sym_with] = ACTIONS(101),
    [anon_sym_it] = ACTIONS(101),
    [anon_sym_in] = ACTIONS(101),
    [anon_sym_range] = ACTIONS(101),
    [anon_sym_int] = ACTIONS(101),
    [anon_sym_float] = ACTIONS(101),
    [anon_sym_string] = ACTIONS(101),
    [anon_sym_bool] = ACTIONS(101),
    [anon_sym_thing] = ACTIONS(101),
    [anon_sym_error] = ACTIONS(101),
    [anon_sym_DOT] = ACTIONS(97),
    [sym_number] = ACTIONS(99),
    [sym_string] = ACTIONS(99),
    [anon_sym_yes] = ACTIONS(101),
    [anon_sym_no] = ACTIONS(101),
    [sym_nil] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(103),
    [sym_identifier] = ACTIONS(105),
    [anon_sym_struct] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_fun] = ACTIONS(105),
    [anon_sym_egg] = ACTIONS(105),
    [anon_sym_rock] = ACTIONS(105),
    [anon_sym_enum] = ACTIONS(105),
    [anon_sym_map] = ACTIONS(105),
    [anon_sym_type] = ACTIONS(105),
    [anon_sym_ayla] = ACTIONS(105),
    [anon_sym_elen] = ACTIONS(105),
    [anon_sym_four] = ACTIONS(105),
    [anon_sym_why] = ACTIONS(105),
    [anon_sym_back] = ACTIONS(105),
    [anon_sym_kitkat] = ACTIONS(105),
    [anon_sym_next] = ACTIONS(105),
    [anon_sym_decide] = ACTIONS(105),
    [anon_sym_when] = ACTIONS(105),
    [anon_sym_otherwise] = ACTIONS(105),
    [anon_sym_spawn] = ACTIONS(105),
    [anon_sym_with] = ACTIONS(105),
    [anon_sym_it] = ACTIONS(105),
    [anon_sym_in] = ACTIONS(105),
    [anon_sym_range] = ACTIONS(105),
    [anon_sym_int] = ACTIONS(105),
    [anon_sym_float] = ACTIONS(105),
    [anon_sym_string] = ACTIONS(105),
    [anon_sym_bool] = ACTIONS(105),
    [anon_sym_thing] = ACTIONS(105),
    [anon_sym_error] = ACTIONS(105),
    [sym_number] = ACTIONS(103),
    [sym_string] = ACTIONS(103),
    [anon_sym_yes] = ACTIONS(105),
    [anon_sym_no] = ACTIONS(105),
    [sym_nil] = ACTIONS(105),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym_identifier] = ACTIONS(109),
    [anon_sym_struct] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(107),
    [anon_sym_fun] = ACTIONS(109),
    [anon_sym_egg] = ACTIONS(109),
    [anon_sym_rock] = ACTIONS(109),
    [anon_sym_enum] = ACTIONS(109),
    [anon_sym_map] = ACTIONS(109),
    [anon_sym_type] = ACTIONS(109),
    [anon_sym_ayla] = ACTIONS(109),
    [anon_sym_elen] = ACTIONS(109),
    [anon_sym_four] = ACTIONS(109),
    [anon_sym_why] = ACTIONS(109),
    [anon_sym_back] = ACTIONS(109),
    [anon_sym_kitkat] = ACTIONS(109),
    [anon_sym_next] = ACTIONS(109),
    [anon_sym_decide] = ACTIONS(109),
    [anon_sym_when] = ACTIONS(109),
    [anon_sym_otherwise] = ACTIONS(109),
    [anon_sym_spawn] = ACTIONS(109),
    [anon_sym_with] = ACTIONS(109),
    [anon_sym_it] = ACTIONS(109),
    [anon_sym_in] = ACTIONS(109),
    [anon_sym_range] = ACTIONS(109),
    [anon_sym_int] = ACTIONS(109),
    [anon_sym_float] = ACTIONS(109),
    [anon_sym_string] = ACTIONS(109),
    [anon_sym_bool] = ACTIONS(109),
    [anon_sym_thing] = ACTIONS(109),
    [anon_sym_error] = ACTIONS(109),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_yes] = ACTIONS(109),
    [anon_sym_no] = ACTIONS(109),
    [sym_nil] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym_identifier] = ACTIONS(113),
    [anon_sym_struct] = ACTIONS(113),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_fun] = ACTIONS(113),
    [anon_sym_egg] = ACTIONS(113),
    [anon_sym_rock] = ACTIONS(113),
    [anon_sym_enum] = ACTIONS(113),
    [anon_sym_map] = ACTIONS(113),
    [anon_sym_type] = ACTIONS(113),
    [anon_sym_ayla] = ACTIONS(113),
    [anon_sym_elen] = ACTIONS(113),
    [anon_sym_four] = ACTIONS(113),
    [anon_sym_why] = ACTIONS(113),
    [anon_sym_back] = ACTIONS(113),
    [anon_sym_kitkat] = ACTIONS(113),
    [anon_sym_next] = ACTIONS(113),
    [anon_sym_decide] = ACTIONS(113),
    [anon_sym_when] = ACTIONS(113),
    [anon_sym_otherwise] = ACTIONS(113),
    [anon_sym_spawn] = ACTIONS(113),
    [anon_sym_with] = ACTIONS(113),
    [anon_sym_it] = ACTIONS(113),
    [anon_sym_in] = ACTIONS(113),
    [anon_sym_range] = ACTIONS(113),
    [anon_sym_int] = ACTIONS(113),
    [anon_sym_float] = ACTIONS(113),
    [anon_sym_string] = ACTIONS(113),
    [anon_sym_bool] = ACTIONS(113),
    [anon_sym_thing] = ACTIONS(113),
    [anon_sym_error] = ACTIONS(113),
    [sym_number] = ACTIONS(111),
    [sym_string] = ACTIONS(111),
    [anon_sym_yes] = ACTIONS(113),
    [anon_sym_no] = ACTIONS(113),
    [sym_nil] = ACTIONS(113),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym_identifier] = ACTIONS(117),
    [anon_sym_struct] = ACTIONS(117),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_fun] = ACTIONS(117),
    [anon_sym_egg] = ACTIONS(117),
    [anon_sym_rock] = ACTIONS(117),
    [anon_sym_enum] = ACTIONS(117),
    [anon_sym_map] = ACTIONS(117),
    [anon_sym_type] = ACTIONS(117),
    [anon_sym_ayla] = ACTIONS(117),
    [anon_sym_elen] = ACTIONS(117),
    [anon_sym_four] = ACTIONS(117),
    [anon_sym_why] = ACTIONS(117),
    [anon_sym_back] = ACTIONS(117),
    [anon_sym_kitkat] = ACTIONS(117),
    [anon_sym_next] = ACTIONS(117),
    [anon_sym_decide] = ACTIONS(117),
    [anon_sym_when] = ACTIONS(117),
    [anon_sym_otherwise] = ACTIONS(117),
    [anon_sym_spawn] = ACTIONS(117),
    [anon_sym_with] = ACTIONS(117),
    [anon_sym_it] = ACTIONS(117),
    [anon_sym_in] = ACTIONS(117),
    [anon_sym_range] = ACTIONS(117),
    [anon_sym_int] = ACTIONS(117),
    [anon_sym_float] = ACTIONS(117),
    [anon_sym_string] = ACTIONS(117),
    [anon_sym_bool] = ACTIONS(117),
    [anon_sym_thing] = ACTIONS(117),
    [anon_sym_error] = ACTIONS(117),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [anon_sym_yes] = ACTIONS(117),
    [anon_sym_no] = ACTIONS(117),
    [sym_nil] = ACTIONS(117),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(25)] = {
    [ts_builtin_sym_end] = ACTIONS(119),
    [sym_identifier] = ACTIONS(121),
    [anon_sym_struct] = ACTIONS(121),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_fun] = ACTIONS(121),
    [anon_sym_egg] = ACTIONS(121),
    [anon_sym_rock] = ACTIONS(121),
    [anon_sym_enum] = ACTIONS(121),
    [anon_sym_map] = ACTIONS(121),
    [anon_sym_type] = ACTIONS(121),
    [anon_sym_ayla] = ACTIONS(121),
    [anon_sym_elen] = ACTIONS(121),
    [anon_sym_four] = ACTIONS(121),
    [anon_sym_why] = ACTIONS(121),
    [anon_sym_back] = ACTIONS(121),
    [anon_sym_kitkat] = ACTIONS(121),
    [anon_sym_next] = ACTIONS(121),
    [anon_sym_decide] = ACTIONS(121),
    [anon_sym_when] = ACTIONS(121),
    [anon_sym_otherwise] = ACTIONS(121),
    [anon_sym_spawn] = ACTIONS(121),
    [anon_sym_with] = ACTIONS(121),
    [anon_sym_it] = ACTIONS(121),
    [anon_sym_in] = ACTIONS(121),
    [anon_sym_range] = ACTIONS(121),
    [anon_sym_int] = ACTIONS(121),
    [anon_sym_float] = ACTIONS(121),
    [anon_sym_string] = ACTIONS(121),
    [anon_sym_bool] = ACTIONS(121),
    [anon_sym_thing] = ACTIONS(121),
    [anon_sym_error] = ACTIONS(121),
    [sym_number] = ACTIONS(119),
    [sym_string] = ACTIONS(119),
    [anon_sym_yes] = ACTIONS(121),
    [anon_sym_no] = ACTIONS(121),
    [sym_nil] = ACTIONS(121),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(26)] = {
    [ts_builtin_sym_end] = ACTIONS(123),
    [sym_identifier] = ACTIONS(125),
    [anon_sym_struct] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(123),
    [anon_sym_fun] = ACTIONS(125),
    [anon_sym_egg] = ACTIONS(125),
    [anon_sym_rock] = ACTIONS(125),
    [anon_sym_enum] = ACTIONS(125),
    [anon_sym_map] = ACTIONS(125),
    [anon_sym_type] = ACTIONS(125),
    [anon_sym_ayla] = ACTIONS(125),
    [anon_sym_elen] = ACTIONS(125),
    [anon_sym_four] = ACTIONS(125),
    [anon_sym_why] = ACTIONS(125),
    [anon_sym_back] = ACTIONS(125),
    [anon_sym_kitkat] = ACTIONS(125),
    [anon_sym_next] = ACTIONS(125),
    [anon_sym_decide] = ACTIONS(125),
    [anon_sym_when] = ACTIONS(125),
    [anon_sym_otherwise] = ACTIONS(125),
    [anon_sym_spawn] = ACTIONS(125),
    [anon_sym_with] = ACTIONS(125),
    [anon_sym_it] = ACTIONS(125),
    [anon_sym_in] = ACTIONS(125),
    [anon_sym_range] = ACTIONS(125),
    [anon_sym_int] = ACTIONS(125),
    [anon_sym_float] = ACTIONS(125),
    [anon_sym_string] = ACTIONS(125),
    [anon_sym_bool] = ACTIONS(125),
    [anon_sym_thing] = ACTIONS(125),
    [anon_sym_error] = ACTIONS(125),
    [sym_number] = ACTIONS(123),
    [sym_string] = ACTIONS(123),
    [anon_sym_yes] = ACTIONS(125),
    [anon_sym_no] = ACTIONS(125),
    [sym_nil] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(27)] = {
    [ts_builtin_sym_end] = ACTIONS(127),
    [sym_identifier] = ACTIONS(129),
    [anon_sym_struct] = ACTIONS(129),
    [anon_sym_RBRACE] = ACTIONS(127),
    [anon_sym_fun] = ACTIONS(129),
    [anon_sym_egg] = ACTIONS(129),
    [anon_sym_rock] = ACTIONS(129),
    [anon_sym_enum] = ACTIONS(129),
    [anon_sym_map] = ACTIONS(129),
    [anon_sym_type] = ACTIONS(129),
    [anon_sym_ayla] = ACTIONS(129),
    [anon_sym_elen] = ACTIONS(129),
    [anon_sym_four] = ACTIONS(129),
    [anon_sym_why] = ACTIONS(129),
    [anon_sym_back] = ACTIONS(129),
    [anon_sym_kitkat] = ACTIONS(129),
    [anon_sym_next] = ACTIONS(129),
    [anon_sym_decide] = ACTIONS(129),
    [anon_sym_when] = ACTIONS(129),
    [anon_sym_otherwise] = ACTIONS(129),
    [anon_sym_spawn] = ACTIONS(129),
    [anon_sym_with] = ACTIONS(129),
    [anon_sym_it] = ACTIONS(129),
    [anon_sym_in] = ACTIONS(129),
    [anon_sym_range] = ACTIONS(129),
    [anon_sym_int] = ACTIONS(129),
    [anon_sym_float] = ACTIONS(129),
    [anon_sym_string] = ACTIONS(129),
    [anon_sym_bool] = ACTIONS(129),
    [anon_sym_thing] = ACTIONS(129),
    [anon_sym_error] = ACTIONS(129),
    [sym_number] = ACTIONS(127),
    [sym_string] = ACTIONS(127),
    [anon_sym_yes] = ACTIONS(129),
    [anon_sym_no] = ACTIONS(129),
    [sym_nil] = ACTIONS(129),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(28)] = {
    [ts_builtin_sym_end] = ACTIONS(131),
    [sym_identifier] = ACTIONS(133),
    [anon_sym_struct] = ACTIONS(133),
    [anon_sym_RBRACE] = ACTIONS(131),
    [anon_sym_fun] = ACTIONS(133),
    [anon_sym_egg] = ACTIONS(133),
    [anon_sym_rock] = ACTIONS(133),
    [anon_sym_enum] = ACTIONS(133),
    [anon_sym_map] = ACTIONS(133),
    [anon_sym_type] = ACTIONS(133),
    [anon_sym_ayla] = ACTIONS(133),
    [anon_sym_elen] = ACTIONS(133),
    [anon_sym_four] = ACTIONS(133),
    [anon_sym_why] = ACTIONS(133),
    [anon_sym_back] = ACTIONS(133),
    [anon_sym_kitkat] = ACTIONS(133),
    [anon_sym_next] = ACTIONS(133),
    [anon_sym_decide] = ACTIONS(133),
    [anon_sym_when] = ACTIONS(133),
    [anon_sym_otherwise] = ACTIONS(133),
    [anon_sym_spawn] = ACTIONS(133),
    [anon_sym_with] = ACTIONS(133),
    [anon_sym_it] = ACTIONS(133),
    [anon_sym_in] = ACTIONS(133),
    [anon_sym_range] = ACTIONS(133),
    [anon_sym_int] = ACTIONS(133),
    [anon_sym_float] = ACTIONS(133),
    [anon_sym_string] = ACTIONS(133),
    [anon_sym_bool] = ACTIONS(133),
    [anon_sym_thing] = ACTIONS(133),
    [anon_sym_error] = ACTIONS(133),
    [sym_number] = ACTIONS(131),
    [sym_string] = ACTIONS(131),
    [anon_sym_yes] = ACTIONS(133),
    [anon_sym_no] = ACTIONS(133),
    [sym_nil] = ACTIONS(133),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(29)] = {
    [ts_builtin_sym_end] = ACTIONS(135),
    [sym_identifier] = ACTIONS(137),
    [anon_sym_struct] = ACTIONS(137),
    [anon_sym_RBRACE] = ACTIONS(135),
    [anon_sym_fun] = ACTIONS(137),
    [anon_sym_egg] = ACTIONS(137),
    [anon_sym_rock] = ACTIONS(137),
    [anon_sym_enum] = ACTIONS(137),
    [anon_sym_map] = ACTIONS(137),
    [anon_sym_type] = ACTIONS(137),
    [anon_sym_ayla] = ACTIONS(137),
    [anon_sym_elen] = ACTIONS(137),
    [anon_sym_four] = ACTIONS(137),
    [anon_sym_why] = ACTIONS(137),
    [anon_sym_back] = ACTIONS(137),
    [anon_sym_kitkat] = ACTIONS(137),
    [anon_sym_next] = ACTIONS(137),
    [anon_sym_decide] = ACTIONS(137),
    [anon_sym_when] = ACTIONS(137),
    [anon_sym_otherwise] = ACTIONS(137),
    [anon_sym_spawn] = ACTIONS(137),
    [anon_sym_with] = ACTIONS(137),
    [anon_sym_it] = ACTIONS(137),
    [anon_sym_in] = ACTIONS(137),
    [anon_sym_range] = ACTIONS(137),
    [anon_sym_int] = ACTIONS(137),
    [anon_sym_float] = ACTIONS(137),
    [anon_sym_string] = ACTIONS(137),
    [anon_sym_bool] = ACTIONS(137),
    [anon_sym_thing] = ACTIONS(137),
    [anon_sym_error] = ACTIONS(137),
    [sym_number] = ACTIONS(135),
    [sym_string] = ACTIONS(135),
    [anon_sym_yes] = ACTIONS(137),
    [anon_sym_no] = ACTIONS(137),
    [sym_nil] = ACTIONS(137),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(30)] = {
    [ts_builtin_sym_end] = ACTIONS(139),
    [sym_identifier] = ACTIONS(141),
    [anon_sym_struct] = ACTIONS(141),
    [anon_sym_RBRACE] = ACTIONS(139),
    [anon_sym_fun] = ACTIONS(141),
    [anon_sym_egg] = ACTIONS(141),
    [anon_sym_rock] = ACTIONS(141),
    [anon_sym_enum] = ACTIONS(141),
    [anon_sym_map] = ACTIONS(141),
    [anon_sym_type] = ACTIONS(141),
    [anon_sym_ayla] = ACTIONS(141),
    [anon_sym_elen] = ACTIONS(141),
    [anon_sym_four] = ACTIONS(141),
    [anon_sym_why] = ACTIONS(141),
    [anon_sym_back] = ACTIONS(141),
    [anon_sym_kitkat] = ACTIONS(141),
    [anon_sym_next] = ACTIONS(141),
    [anon_sym_decide] = ACTIONS(141),
    [anon_sym_when] = ACTIONS(141),
    [anon_sym_otherwise] = ACTIONS(141),
    [anon_sym_spawn] = ACTIONS(141),
    [anon_sym_with] = ACTIONS(141),
    [anon_sym_it] = ACTIONS(141),
    [anon_sym_in] = ACTIONS(141),
    [anon_sym_range] = ACTIONS(141),
    [anon_sym_int] = ACTIONS(141),
    [anon_sym_float] = ACTIONS(141),
    [anon_sym_string] = ACTIONS(141),
    [anon_sym_bool] = ACTIONS(141),
    [anon_sym_thing] = ACTIONS(141),
    [anon_sym_error] = ACTIONS(141),
    [sym_number] = ACTIONS(139),
    [sym_string] = ACTIONS(139),
    [anon_sym_yes] = ACTIONS(141),
    [anon_sym_no] = ACTIONS(141),
    [sym_nil] = ACTIONS(141),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(31)] = {
    [ts_builtin_sym_end] = ACTIONS(143),
    [sym_identifier] = ACTIONS(145),
    [anon_sym_struct] = ACTIONS(145),
    [anon_sym_RBRACE] = ACTIONS(143),
    [anon_sym_fun] = ACTIONS(145),
    [anon_sym_egg] = ACTIONS(145),
    [anon_sym_rock] = ACTIONS(145),
    [anon_sym_enum] = ACTIONS(145),
    [anon_sym_map] = ACTIONS(145),
    [anon_sym_type] = ACTIONS(145),
    [anon_sym_ayla] = ACTIONS(145),
    [anon_sym_elen] = ACTIONS(145),
    [anon_sym_four] = ACTIONS(145),
    [anon_sym_why] = ACTIONS(145),
    [anon_sym_back] = ACTIONS(145),
    [anon_sym_kitkat] = ACTIONS(145),
    [anon_sym_next] = ACTIONS(145),
    [anon_sym_decide] = ACTIONS(145),
    [anon_sym_when] = ACTIONS(145),
    [anon_sym_otherwise] = ACTIONS(145),
    [anon_sym_spawn] = ACTIONS(145),
    [anon_sym_with] = ACTIONS(145),
    [anon_sym_it] = ACTIONS(145),
    [anon_sym_in] = ACTIONS(145),
    [anon_sym_range] = ACTIONS(145),
    [anon_sym_int] = ACTIONS(145),
    [anon_sym_float] = ACTIONS(145),
    [anon_sym_string] = ACTIONS(145),
    [anon_sym_bool] = ACTIONS(145),
    [anon_sym_thing] = ACTIONS(145),
    [anon_sym_error] = ACTIONS(145),
    [sym_number] = ACTIONS(143),
    [sym_string] = ACTIONS(143),
    [anon_sym_yes] = ACTIONS(145),
    [anon_sym_no] = ACTIONS(145),
    [sym_nil] = ACTIONS(145),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(32)] = {
    [ts_builtin_sym_end] = ACTIONS(147),
    [sym_identifier] = ACTIONS(149),
    [anon_sym_struct] = ACTIONS(149),
    [anon_sym_RBRACE] = ACTIONS(147),
    [anon_sym_fun] = ACTIONS(149),
    [anon_sym_egg] = ACTIONS(149),
    [anon_sym_rock] = ACTIONS(149),
    [anon_sym_enum] = ACTIONS(149),
    [anon_sym_map] = ACTIONS(149),
    [anon_sym_type] = ACTIONS(149),
    [anon_sym_ayla] = ACTIONS(149),
    [anon_sym_elen] = ACTIONS(149),
    [anon_sym_four] = ACTIONS(149),
    [anon_sym_why] = ACTIONS(149),
    [anon_sym_back] = ACTIONS(149),
    [anon_sym_kitkat] = ACTIONS(149),
    [anon_sym_next] = ACTIONS(149),
    [anon_sym_decide] = ACTIONS(149),
    [anon_sym_when] = ACTIONS(149),
    [anon_sym_otherwise] = ACTIONS(149),
    [anon_sym_spawn] = ACTIONS(149),
    [anon_sym_with] = ACTIONS(149),
    [anon_sym_it] = ACTIONS(149),
    [anon_sym_in] = ACTIONS(149),
    [anon_sym_range] = ACTIONS(149),
    [anon_sym_int] = ACTIONS(149),
    [anon_sym_float] = ACTIONS(149),
    [anon_sym_string] = ACTIONS(149),
    [anon_sym_bool] = ACTIONS(149),
    [anon_sym_thing] = ACTIONS(149),
    [anon_sym_error] = ACTIONS(149),
    [sym_number] = ACTIONS(147),
    [sym_string] = ACTIONS(147),
    [anon_sym_yes] = ACTIONS(149),
    [anon_sym_no] = ACTIONS(149),
    [sym_nil] = ACTIONS(149),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_type_identifier,
    STATE(67), 1,
      sym_primitive_type,
    ACTIONS(151), 6,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_bool,
      anon_sym_thing,
      anon_sym_error,
  [18] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_type_identifier,
    STATE(57), 1,
      sym_primitive_type,
    ACTIONS(151), 6,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_bool,
      anon_sym_thing,
      anon_sym_error,
  [36] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_type_identifier,
    STATE(60), 1,
      sym_primitive_type,
    ACTIONS(151), 6,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_bool,
      anon_sym_thing,
      anon_sym_error,
  [54] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_argument_list_repeat1,
  [70] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_block,
    STATE(53), 1,
      sym_return_type,
  [86] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [100] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [114] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_block,
    STATE(54), 1,
      sym_return_type,
  [130] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_block,
    STATE(58), 1,
      sym_return_type,
  [146] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(39), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [160] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_block,
    STATE(55), 1,
      sym_return_type,
  [176] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_parameter_list,
  [189] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_parameter_list_repeat1,
  [202] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_argument_list_repeat1,
  [215] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [226] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_parameter_list_repeat1,
  [239] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_parameter_list,
  [252] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_receiver,
  [265] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_parameter_list_repeat1,
  [278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_argument_list_repeat1,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_block,
  [301] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_block,
  [311] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_block,
  [321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_block,
  [347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_identifier,
  [354] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
  [361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
  [368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
  [375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
  [382] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_identifier,
  [389] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_identifier,
  [396] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
  [403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
  [410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [417] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
  [424] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
  [431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
  [438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_identifier,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(33)] = 0,
  [SMALL_STATE(34)] = 18,
  [SMALL_STATE(35)] = 36,
  [SMALL_STATE(36)] = 54,
  [SMALL_STATE(37)] = 70,
  [SMALL_STATE(38)] = 86,
  [SMALL_STATE(39)] = 100,
  [SMALL_STATE(40)] = 114,
  [SMALL_STATE(41)] = 130,
  [SMALL_STATE(42)] = 146,
  [SMALL_STATE(43)] = 160,
  [SMALL_STATE(44)] = 176,
  [SMALL_STATE(45)] = 189,
  [SMALL_STATE(46)] = 202,
  [SMALL_STATE(47)] = 215,
  [SMALL_STATE(48)] = 226,
  [SMALL_STATE(49)] = 239,
  [SMALL_STATE(50)] = 252,
  [SMALL_STATE(51)] = 265,
  [SMALL_STATE(52)] = 278,
  [SMALL_STATE(53)] = 291,
  [SMALL_STATE(54)] = 301,
  [SMALL_STATE(55)] = 311,
  [SMALL_STATE(56)] = 321,
  [SMALL_STATE(57)] = 329,
  [SMALL_STATE(58)] = 337,
  [SMALL_STATE(59)] = 347,
  [SMALL_STATE(60)] = 354,
  [SMALL_STATE(61)] = 361,
  [SMALL_STATE(62)] = 368,
  [SMALL_STATE(63)] = 375,
  [SMALL_STATE(64)] = 382,
  [SMALL_STATE(65)] = 389,
  [SMALL_STATE(66)] = 396,
  [SMALL_STATE(67)] = 403,
  [SMALL_STATE(68)] = 410,
  [SMALL_STATE(69)] = 417,
  [SMALL_STATE(70)] = 424,
  [SMALL_STATE(71)] = 431,
  [SMALL_STATE(72)] = 438,
  [SMALL_STATE(73)] = 445,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, 0, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, 0, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 8, 0, 13),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 8, 0, 13),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_decl, 5, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 4, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_decl, 4, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 5, 0, 7),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 5, 0, 7),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 8),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 6, 0, 8),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 9),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 6, 0, 9),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 11),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 7, 0, 11),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 7),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 6, 0, 7),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 12),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 7, 0, 12),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 9),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 7, 0, 9),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 2, 0, 5),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 3, 0, 10),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_receiver, 4, 0, 6),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ayla(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
