/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 26
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 44
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_EQ = 2,
  anon_sym_struct = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_fun = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_egg = 10,
  anon_sym_rock = 11,
  anon_sym_enum = 12,
  anon_sym_map = 13,
  anon_sym_type = 14,
  anon_sym_ayla = 15,
  anon_sym_elen = 16,
  anon_sym_four = 17,
  anon_sym_why = 18,
  anon_sym_back = 19,
  anon_sym_kitkat = 20,
  anon_sym_next = 21,
  anon_sym_decide = 22,
  anon_sym_when = 23,
  anon_sym_otherwise = 24,
  anon_sym_spawn = 25,
  anon_sym_with = 26,
  anon_sym_it = 27,
  anon_sym_in = 28,
  anon_sym_range = 29,
  anon_sym_int = 30,
  anon_sym_float = 31,
  anon_sym_string = 32,
  anon_sym_bool = 33,
  anon_sym_thing = 34,
  anon_sym_error = 35,
  anon_sym_DOT = 36,
  sym_type_identifier = 37,
  sym_number = 38,
  sym_string = 39,
  anon_sym_yes = 40,
  anon_sym_no = 41,
  sym_nil = 42,
  sym_comment = 43,
  sym_source_file = 44,
  sym__statement = 45,
  sym_assignment = 46,
  sym_struct_decl = 47,
  sym_struct_field = 48,
  sym_function_decl = 49,
  sym_parameter_list = 50,
  sym_block = 51,
  sym_keyword = 52,
  sym_primitive_type = 53,
  sym_expression = 54,
  sym_call_expression = 55,
  sym_member_expression = 56,
  sym_argument_list = 57,
  sym_boolean = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym_struct_decl_repeat1 = 60,
  aux_sym_parameter_list_repeat1 = 61,
  aux_sym_argument_list_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fun] = "fun",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_egg] = "egg",
  [anon_sym_rock] = "rock",
  [anon_sym_enum] = "enum",
  [anon_sym_map] = "map",
  [anon_sym_type] = "type",
  [anon_sym_ayla] = "ayla",
  [anon_sym_elen] = "elen",
  [anon_sym_four] = "four",
  [anon_sym_why] = "why",
  [anon_sym_back] = "back",
  [anon_sym_kitkat] = "kitkat",
  [anon_sym_next] = "next",
  [anon_sym_decide] = "decide",
  [anon_sym_when] = "when",
  [anon_sym_otherwise] = "otherwise",
  [anon_sym_spawn] = "spawn",
  [anon_sym_with] = "with",
  [anon_sym_it] = "it",
  [anon_sym_in] = "in",
  [anon_sym_range] = "range",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_string] = "string",
  [anon_sym_bool] = "bool",
  [anon_sym_thing] = "thing",
  [anon_sym_error] = "error",
  [anon_sym_DOT] = ".",
  [sym_type_identifier] = "type_identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [sym_nil] = "nil",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_assignment] = "assignment",
  [sym_struct_decl] = "struct_decl",
  [sym_struct_field] = "struct_field",
  [sym_function_decl] = "function_decl",
  [sym_parameter_list] = "parameter_list",
  [sym_block] = "block",
  [sym_keyword] = "keyword",
  [sym_primitive_type] = "primitive_type",
  [sym_expression] = "expression",
  [sym_call_expression] = "call_expression",
  [sym_member_expression] = "member_expression",
  [sym_argument_list] = "argument_list",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_decl_repeat1] = "struct_decl_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_egg] = anon_sym_egg,
  [anon_sym_rock] = anon_sym_rock,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_ayla] = anon_sym_ayla,
  [anon_sym_elen] = anon_sym_elen,
  [anon_sym_four] = anon_sym_four,
  [anon_sym_why] = anon_sym_why,
  [anon_sym_back] = anon_sym_back,
  [anon_sym_kitkat] = anon_sym_kitkat,
  [anon_sym_next] = anon_sym_next,
  [anon_sym_decide] = anon_sym_decide,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_otherwise] = anon_sym_otherwise,
  [anon_sym_spawn] = anon_sym_spawn,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_it] = anon_sym_it,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_range] = anon_sym_range,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_thing] = anon_sym_thing,
  [anon_sym_error] = anon_sym_error,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_type_identifier] = sym_type_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [sym_nil] = sym_nil,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_assignment] = sym_assignment,
  [sym_struct_decl] = sym_struct_decl,
  [sym_struct_field] = sym_struct_field,
  [sym_function_decl] = sym_function_decl,
  [sym_parameter_list] = sym_parameter_list,
  [sym_block] = sym_block,
  [sym_keyword] = sym_keyword,
  [sym_primitive_type] = sym_primitive_type,
  [sym_expression] = sym_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_member_expression] = sym_member_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_decl_repeat1] = aux_sym_struct_decl_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_egg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ayla] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_four] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_why] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_back] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_kitkat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_next] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decide] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_otherwise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spawn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_it] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_thing] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_function = 1,
  field_keyword = 2,
  field_left = 3,
  field_name = 4,
  field_object = 5,
  field_property = 6,
  field_right = 7,
  field_type = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_keyword] = "keyword",
  [field_left] = "left",
  [field_name] = "name",
  [field_object] = "object",
  [field_property] = "property",
  [field_right] = "right",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_right, 2},
  [2] =
    {field_function, 0},
  [3] =
    {field_object, 0},
    {field_property, 2},
  [5] =
    {field_keyword, 0},
    {field_name, 1},
  [7] =
    {field_name, 0},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 1,
        '(', 9,
        ')', 10,
        ',', 11,
        '.', 12,
        '/', 2,
        '=', 6,
        '{', 7,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'd', 3,
        'e', 4,
        'f', 5,
        'i', 6,
        'k', 7,
        'm', 8,
        'n', 9,
        'o', 10,
        'r', 11,
        's', 12,
        't', 13,
        'w', 14,
        'y', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'g') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(37);
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(39);
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_it);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'x') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_no);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 36:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(67);
      if (lookahead == 'y') ADVANCE(68);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 45:
      if (lookahead == 'k') ADVANCE(72);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_egg);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 50:
      if (lookahead == 'm') ADVANCE(76);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(77);
      END_STATE();
    case 52:
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 56:
      if (lookahead == 'k') ADVANCE(80);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'g') ADVANCE(83);
      END_STATE();
    case 62:
      if (lookahead == 'k') ADVANCE(84);
      END_STATE();
    case 63:
      if (lookahead == 'w') ADVANCE(85);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(86);
      if (lookahead == 'u') ADVANCE(87);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_why);
      END_STATE();
    case 69:
      if (lookahead == 'h') ADVANCE(91);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_yes);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_ayla);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_back);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 74:
      if (lookahead == 'd') ADVANCE(92);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_elen);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_four);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_next);
      END_STATE();
    case 82:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 83:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_rock);
      END_STATE();
    case 85:
      if (lookahead == 'n') ADVANCE(98);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 87:
      if (lookahead == 'c') ADVANCE(100);
      END_STATE();
    case 88:
      if (lookahead == 'g') ADVANCE(101);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 92:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_error);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 95:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 96:
      if (lookahead == 'w') ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_spawn);
      END_STATE();
    case 99:
      if (lookahead == 'g') ADVANCE(105);
      END_STATE();
    case 100:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_thing);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_decide);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_kitkat);
      END_STATE();
    case 104:
      if (lookahead == 'i') ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 107:
      if (lookahead == 's') ADVANCE(108);
      END_STATE();
    case 108:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_otherwise);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_egg] = ACTIONS(1),
    [anon_sym_rock] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_ayla] = ACTIONS(1),
    [anon_sym_elen] = ACTIONS(1),
    [anon_sym_four] = ACTIONS(1),
    [anon_sym_why] = ACTIONS(1),
    [anon_sym_back] = ACTIONS(1),
    [anon_sym_kitkat] = ACTIONS(1),
    [anon_sym_next] = ACTIONS(1),
    [anon_sym_decide] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_otherwise] = ACTIONS(1),
    [anon_sym_spawn] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_it] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_thing] = ACTIONS(1),
    [anon_sym_error] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(49),
    [sym__statement] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_struct_decl] = STATE(3),
    [sym_function_decl] = STATE(3),
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(18),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_struct_decl] = STATE(2),
    [sym_function_decl] = STATE(2),
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(18),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_struct] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_fun] = ACTIONS(31),
    [anon_sym_egg] = ACTIONS(34),
    [anon_sym_rock] = ACTIONS(34),
    [anon_sym_enum] = ACTIONS(34),
    [anon_sym_map] = ACTIONS(34),
    [anon_sym_type] = ACTIONS(34),
    [anon_sym_ayla] = ACTIONS(34),
    [anon_sym_elen] = ACTIONS(34),
    [anon_sym_four] = ACTIONS(34),
    [anon_sym_why] = ACTIONS(34),
    [anon_sym_back] = ACTIONS(34),
    [anon_sym_kitkat] = ACTIONS(34),
    [anon_sym_next] = ACTIONS(34),
    [anon_sym_decide] = ACTIONS(34),
    [anon_sym_when] = ACTIONS(34),
    [anon_sym_otherwise] = ACTIONS(34),
    [anon_sym_spawn] = ACTIONS(34),
    [anon_sym_with] = ACTIONS(34),
    [anon_sym_it] = ACTIONS(34),
    [anon_sym_in] = ACTIONS(34),
    [anon_sym_range] = ACTIONS(34),
    [anon_sym_int] = ACTIONS(37),
    [anon_sym_float] = ACTIONS(37),
    [anon_sym_string] = ACTIONS(37),
    [anon_sym_bool] = ACTIONS(37),
    [anon_sym_thing] = ACTIONS(37),
    [anon_sym_error] = ACTIONS(37),
    [sym_number] = ACTIONS(40),
    [sym_string] = ACTIONS(40),
    [anon_sym_yes] = ACTIONS(43),
    [anon_sym_no] = ACTIONS(43),
    [sym_nil] = ACTIONS(46),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_struct_decl] = STATE(2),
    [sym_function_decl] = STATE(2),
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(18),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(5),
    [sym_assignment] = STATE(5),
    [sym_struct_decl] = STATE(5),
    [sym_function_decl] = STATE(5),
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(18),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_struct_decl] = STATE(2),
    [sym_function_decl] = STATE(2),
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(18),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_fun] = ACTIONS(11),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(29),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_argument_list] = STATE(44),
    [sym_boolean] = STATE(9),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_struct] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_egg] = ACTIONS(61),
    [anon_sym_rock] = ACTIONS(61),
    [anon_sym_enum] = ACTIONS(61),
    [anon_sym_map] = ACTIONS(61),
    [anon_sym_type] = ACTIONS(61),
    [anon_sym_ayla] = ACTIONS(61),
    [anon_sym_elen] = ACTIONS(61),
    [anon_sym_four] = ACTIONS(61),
    [anon_sym_why] = ACTIONS(61),
    [anon_sym_back] = ACTIONS(61),
    [anon_sym_kitkat] = ACTIONS(61),
    [anon_sym_next] = ACTIONS(61),
    [anon_sym_decide] = ACTIONS(61),
    [anon_sym_when] = ACTIONS(61),
    [anon_sym_otherwise] = ACTIONS(61),
    [anon_sym_spawn] = ACTIONS(61),
    [anon_sym_with] = ACTIONS(61),
    [anon_sym_it] = ACTIONS(61),
    [anon_sym_in] = ACTIONS(61),
    [anon_sym_range] = ACTIONS(61),
    [anon_sym_int] = ACTIONS(61),
    [anon_sym_float] = ACTIONS(61),
    [anon_sym_string] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(61),
    [anon_sym_thing] = ACTIONS(61),
    [anon_sym_error] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_yes] = ACTIONS(61),
    [anon_sym_no] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [anon_sym_struct] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_fun] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [anon_sym_egg] = ACTIONS(67),
    [anon_sym_rock] = ACTIONS(67),
    [anon_sym_enum] = ACTIONS(67),
    [anon_sym_map] = ACTIONS(67),
    [anon_sym_type] = ACTIONS(67),
    [anon_sym_ayla] = ACTIONS(67),
    [anon_sym_elen] = ACTIONS(67),
    [anon_sym_four] = ACTIONS(67),
    [anon_sym_why] = ACTIONS(67),
    [anon_sym_back] = ACTIONS(67),
    [anon_sym_kitkat] = ACTIONS(67),
    [anon_sym_next] = ACTIONS(67),
    [anon_sym_decide] = ACTIONS(67),
    [anon_sym_when] = ACTIONS(67),
    [anon_sym_otherwise] = ACTIONS(67),
    [anon_sym_spawn] = ACTIONS(67),
    [anon_sym_with] = ACTIONS(67),
    [anon_sym_it] = ACTIONS(67),
    [anon_sym_in] = ACTIONS(67),
    [anon_sym_range] = ACTIONS(67),
    [anon_sym_int] = ACTIONS(67),
    [anon_sym_float] = ACTIONS(67),
    [anon_sym_string] = ACTIONS(67),
    [anon_sym_bool] = ACTIONS(67),
    [anon_sym_thing] = ACTIONS(67),
    [anon_sym_error] = ACTIONS(67),
    [anon_sym_DOT] = ACTIONS(65),
    [sym_number] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_yes] = ACTIONS(67),
    [anon_sym_no] = ACTIONS(67),
    [sym_nil] = ACTIONS(67),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_struct] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_egg] = ACTIONS(61),
    [anon_sym_rock] = ACTIONS(61),
    [anon_sym_enum] = ACTIONS(61),
    [anon_sym_map] = ACTIONS(61),
    [anon_sym_type] = ACTIONS(61),
    [anon_sym_ayla] = ACTIONS(61),
    [anon_sym_elen] = ACTIONS(61),
    [anon_sym_four] = ACTIONS(61),
    [anon_sym_why] = ACTIONS(61),
    [anon_sym_back] = ACTIONS(61),
    [anon_sym_kitkat] = ACTIONS(61),
    [anon_sym_next] = ACTIONS(61),
    [anon_sym_decide] = ACTIONS(61),
    [anon_sym_when] = ACTIONS(61),
    [anon_sym_otherwise] = ACTIONS(61),
    [anon_sym_spawn] = ACTIONS(61),
    [anon_sym_with] = ACTIONS(61),
    [anon_sym_it] = ACTIONS(61),
    [anon_sym_in] = ACTIONS(61),
    [anon_sym_range] = ACTIONS(61),
    [anon_sym_int] = ACTIONS(61),
    [anon_sym_float] = ACTIONS(61),
    [anon_sym_string] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(61),
    [anon_sym_thing] = ACTIONS(61),
    [anon_sym_error] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_yes] = ACTIONS(61),
    [anon_sym_no] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_struct] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_fun] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_egg] = ACTIONS(71),
    [anon_sym_rock] = ACTIONS(71),
    [anon_sym_enum] = ACTIONS(71),
    [anon_sym_map] = ACTIONS(71),
    [anon_sym_type] = ACTIONS(71),
    [anon_sym_ayla] = ACTIONS(71),
    [anon_sym_elen] = ACTIONS(71),
    [anon_sym_four] = ACTIONS(71),
    [anon_sym_why] = ACTIONS(71),
    [anon_sym_back] = ACTIONS(71),
    [anon_sym_kitkat] = ACTIONS(71),
    [anon_sym_next] = ACTIONS(71),
    [anon_sym_decide] = ACTIONS(71),
    [anon_sym_when] = ACTIONS(71),
    [anon_sym_otherwise] = ACTIONS(71),
    [anon_sym_spawn] = ACTIONS(71),
    [anon_sym_with] = ACTIONS(71),
    [anon_sym_it] = ACTIONS(71),
    [anon_sym_in] = ACTIONS(71),
    [anon_sym_range] = ACTIONS(71),
    [anon_sym_int] = ACTIONS(71),
    [anon_sym_float] = ACTIONS(71),
    [anon_sym_string] = ACTIONS(71),
    [anon_sym_bool] = ACTIONS(71),
    [anon_sym_thing] = ACTIONS(71),
    [anon_sym_error] = ACTIONS(71),
    [anon_sym_DOT] = ACTIONS(69),
    [sym_number] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [anon_sym_yes] = ACTIONS(71),
    [anon_sym_no] = ACTIONS(71),
    [sym_nil] = ACTIONS(71),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_EQ] = ACTIONS(73),
    [anon_sym_struct] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_fun] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_egg] = ACTIONS(61),
    [anon_sym_rock] = ACTIONS(61),
    [anon_sym_enum] = ACTIONS(61),
    [anon_sym_map] = ACTIONS(61),
    [anon_sym_type] = ACTIONS(61),
    [anon_sym_ayla] = ACTIONS(61),
    [anon_sym_elen] = ACTIONS(61),
    [anon_sym_four] = ACTIONS(61),
    [anon_sym_why] = ACTIONS(61),
    [anon_sym_back] = ACTIONS(61),
    [anon_sym_kitkat] = ACTIONS(61),
    [anon_sym_next] = ACTIONS(61),
    [anon_sym_decide] = ACTIONS(61),
    [anon_sym_when] = ACTIONS(61),
    [anon_sym_otherwise] = ACTIONS(61),
    [anon_sym_spawn] = ACTIONS(61),
    [anon_sym_with] = ACTIONS(61),
    [anon_sym_it] = ACTIONS(61),
    [anon_sym_in] = ACTIONS(61),
    [anon_sym_range] = ACTIONS(61),
    [anon_sym_int] = ACTIONS(61),
    [anon_sym_float] = ACTIONS(61),
    [anon_sym_string] = ACTIONS(61),
    [anon_sym_bool] = ACTIONS(61),
    [anon_sym_thing] = ACTIONS(61),
    [anon_sym_error] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_yes] = ACTIONS(61),
    [anon_sym_no] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [sym_identifier] = ACTIONS(77),
    [anon_sym_struct] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_fun] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_egg] = ACTIONS(77),
    [anon_sym_rock] = ACTIONS(77),
    [anon_sym_enum] = ACTIONS(77),
    [anon_sym_map] = ACTIONS(77),
    [anon_sym_type] = ACTIONS(77),
    [anon_sym_ayla] = ACTIONS(77),
    [anon_sym_elen] = ACTIONS(77),
    [anon_sym_four] = ACTIONS(77),
    [anon_sym_why] = ACTIONS(77),
    [anon_sym_back] = ACTIONS(77),
    [anon_sym_kitkat] = ACTIONS(77),
    [anon_sym_next] = ACTIONS(77),
    [anon_sym_decide] = ACTIONS(77),
    [anon_sym_when] = ACTIONS(77),
    [anon_sym_otherwise] = ACTIONS(77),
    [anon_sym_spawn] = ACTIONS(77),
    [anon_sym_with] = ACTIONS(77),
    [anon_sym_it] = ACTIONS(77),
    [anon_sym_in] = ACTIONS(77),
    [anon_sym_range] = ACTIONS(77),
    [anon_sym_int] = ACTIONS(77),
    [anon_sym_float] = ACTIONS(77),
    [anon_sym_string] = ACTIONS(77),
    [anon_sym_bool] = ACTIONS(77),
    [anon_sym_thing] = ACTIONS(77),
    [anon_sym_error] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_yes] = ACTIONS(77),
    [anon_sym_no] = ACTIONS(77),
    [sym_nil] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_identifier] = ACTIONS(81),
    [anon_sym_struct] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_fun] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_egg] = ACTIONS(81),
    [anon_sym_rock] = ACTIONS(81),
    [anon_sym_enum] = ACTIONS(81),
    [anon_sym_map] = ACTIONS(81),
    [anon_sym_type] = ACTIONS(81),
    [anon_sym_ayla] = ACTIONS(81),
    [anon_sym_elen] = ACTIONS(81),
    [anon_sym_four] = ACTIONS(81),
    [anon_sym_why] = ACTIONS(81),
    [anon_sym_back] = ACTIONS(81),
    [anon_sym_kitkat] = ACTIONS(81),
    [anon_sym_next] = ACTIONS(81),
    [anon_sym_decide] = ACTIONS(81),
    [anon_sym_when] = ACTIONS(81),
    [anon_sym_otherwise] = ACTIONS(81),
    [anon_sym_spawn] = ACTIONS(81),
    [anon_sym_with] = ACTIONS(81),
    [anon_sym_it] = ACTIONS(81),
    [anon_sym_in] = ACTIONS(81),
    [anon_sym_range] = ACTIONS(81),
    [anon_sym_int] = ACTIONS(81),
    [anon_sym_float] = ACTIONS(81),
    [anon_sym_string] = ACTIONS(81),
    [anon_sym_bool] = ACTIONS(81),
    [anon_sym_thing] = ACTIONS(81),
    [anon_sym_error] = ACTIONS(81),
    [anon_sym_DOT] = ACTIONS(79),
    [sym_number] = ACTIONS(79),
    [sym_string] = ACTIONS(79),
    [anon_sym_yes] = ACTIONS(81),
    [anon_sym_no] = ACTIONS(81),
    [sym_nil] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_identifier] = ACTIONS(85),
    [anon_sym_struct] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(83),
    [anon_sym_fun] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_COMMA] = ACTIONS(83),
    [anon_sym_egg] = ACTIONS(85),
    [anon_sym_rock] = ACTIONS(85),
    [anon_sym_enum] = ACTIONS(85),
    [anon_sym_map] = ACTIONS(85),
    [anon_sym_type] = ACTIONS(85),
    [anon_sym_ayla] = ACTIONS(85),
    [anon_sym_elen] = ACTIONS(85),
    [anon_sym_four] = ACTIONS(85),
    [anon_sym_why] = ACTIONS(85),
    [anon_sym_back] = ACTIONS(85),
    [anon_sym_kitkat] = ACTIONS(85),
    [anon_sym_next] = ACTIONS(85),
    [anon_sym_decide] = ACTIONS(85),
    [anon_sym_when] = ACTIONS(85),
    [anon_sym_otherwise] = ACTIONS(85),
    [anon_sym_spawn] = ACTIONS(85),
    [anon_sym_with] = ACTIONS(85),
    [anon_sym_it] = ACTIONS(85),
    [anon_sym_in] = ACTIONS(85),
    [anon_sym_range] = ACTIONS(85),
    [anon_sym_int] = ACTIONS(85),
    [anon_sym_float] = ACTIONS(85),
    [anon_sym_string] = ACTIONS(85),
    [anon_sym_bool] = ACTIONS(85),
    [anon_sym_thing] = ACTIONS(85),
    [anon_sym_error] = ACTIONS(85),
    [anon_sym_DOT] = ACTIONS(83),
    [sym_number] = ACTIONS(83),
    [sym_string] = ACTIONS(83),
    [anon_sym_yes] = ACTIONS(85),
    [anon_sym_no] = ACTIONS(85),
    [sym_nil] = ACTIONS(85),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(87),
    [sym_identifier] = ACTIONS(89),
    [anon_sym_struct] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_fun] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_COMMA] = ACTIONS(87),
    [anon_sym_egg] = ACTIONS(89),
    [anon_sym_rock] = ACTIONS(89),
    [anon_sym_enum] = ACTIONS(89),
    [anon_sym_map] = ACTIONS(89),
    [anon_sym_type] = ACTIONS(89),
    [anon_sym_ayla] = ACTIONS(89),
    [anon_sym_elen] = ACTIONS(89),
    [anon_sym_four] = ACTIONS(89),
    [anon_sym_why] = ACTIONS(89),
    [anon_sym_back] = ACTIONS(89),
    [anon_sym_kitkat] = ACTIONS(89),
    [anon_sym_next] = ACTIONS(89),
    [anon_sym_decide] = ACTIONS(89),
    [anon_sym_when] = ACTIONS(89),
    [anon_sym_otherwise] = ACTIONS(89),
    [anon_sym_spawn] = ACTIONS(89),
    [anon_sym_with] = ACTIONS(89),
    [anon_sym_it] = ACTIONS(89),
    [anon_sym_in] = ACTIONS(89),
    [anon_sym_range] = ACTIONS(89),
    [anon_sym_int] = ACTIONS(89),
    [anon_sym_float] = ACTIONS(89),
    [anon_sym_string] = ACTIONS(89),
    [anon_sym_bool] = ACTIONS(89),
    [anon_sym_thing] = ACTIONS(89),
    [anon_sym_error] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(87),
    [sym_number] = ACTIONS(87),
    [sym_string] = ACTIONS(87),
    [anon_sym_yes] = ACTIONS(89),
    [anon_sym_no] = ACTIONS(89),
    [sym_nil] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(19),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [sym_keyword] = STATE(9),
    [sym_primitive_type] = STATE(9),
    [sym_expression] = STATE(34),
    [sym_call_expression] = STATE(9),
    [sym_member_expression] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_egg] = ACTIONS(13),
    [anon_sym_rock] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_ayla] = ACTIONS(13),
    [anon_sym_elen] = ACTIONS(13),
    [anon_sym_four] = ACTIONS(13),
    [anon_sym_why] = ACTIONS(13),
    [anon_sym_back] = ACTIONS(13),
    [anon_sym_kitkat] = ACTIONS(13),
    [anon_sym_next] = ACTIONS(13),
    [anon_sym_decide] = ACTIONS(13),
    [anon_sym_when] = ACTIONS(13),
    [anon_sym_otherwise] = ACTIONS(13),
    [anon_sym_spawn] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_it] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_range] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_thing] = ACTIONS(15),
    [anon_sym_error] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(91),
    [sym_identifier] = ACTIONS(93),
    [anon_sym_struct] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_fun] = ACTIONS(93),
    [anon_sym_egg] = ACTIONS(93),
    [anon_sym_rock] = ACTIONS(93),
    [anon_sym_enum] = ACTIONS(93),
    [anon_sym_map] = ACTIONS(93),
    [anon_sym_type] = ACTIONS(93),
    [anon_sym_ayla] = ACTIONS(93),
    [anon_sym_elen] = ACTIONS(93),
    [anon_sym_four] = ACTIONS(93),
    [anon_sym_why] = ACTIONS(93),
    [anon_sym_back] = ACTIONS(93),
    [anon_sym_kitkat] = ACTIONS(93),
    [anon_sym_next] = ACTIONS(93),
    [anon_sym_decide] = ACTIONS(93),
    [anon_sym_when] = ACTIONS(93),
    [anon_sym_otherwise] = ACTIONS(93),
    [anon_sym_spawn] = ACTIONS(93),
    [anon_sym_with] = ACTIONS(93),
    [anon_sym_it] = ACTIONS(93),
    [anon_sym_in] = ACTIONS(93),
    [anon_sym_range] = ACTIONS(93),
    [anon_sym_int] = ACTIONS(93),
    [anon_sym_float] = ACTIONS(93),
    [anon_sym_string] = ACTIONS(93),
    [anon_sym_bool] = ACTIONS(93),
    [anon_sym_thing] = ACTIONS(93),
    [anon_sym_error] = ACTIONS(93),
    [anon_sym_DOT] = ACTIONS(95),
    [sym_number] = ACTIONS(91),
    [sym_string] = ACTIONS(91),
    [anon_sym_yes] = ACTIONS(93),
    [anon_sym_no] = ACTIONS(93),
    [sym_nil] = ACTIONS(93),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_identifier] = ACTIONS(99),
    [anon_sym_struct] = ACTIONS(99),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_fun] = ACTIONS(99),
    [anon_sym_egg] = ACTIONS(99),
    [anon_sym_rock] = ACTIONS(99),
    [anon_sym_enum] = ACTIONS(99),
    [anon_sym_map] = ACTIONS(99),
    [anon_sym_type] = ACTIONS(99),
    [anon_sym_ayla] = ACTIONS(99),
    [anon_sym_elen] = ACTIONS(99),
    [anon_sym_four] = ACTIONS(99),
    [anon_sym_why] = ACTIONS(99),
    [anon_sym_back] = ACTIONS(99),
    [anon_sym_kitkat] = ACTIONS(99),
    [anon_sym_next] = ACTIONS(99),
    [anon_sym_decide] = ACTIONS(99),
    [anon_sym_when] = ACTIONS(99),
    [anon_sym_otherwise] = ACTIONS(99),
    [anon_sym_spawn] = ACTIONS(99),
    [anon_sym_with] = ACTIONS(99),
    [anon_sym_it] = ACTIONS(99),
    [anon_sym_in] = ACTIONS(99),
    [anon_sym_range] = ACTIONS(99),
    [anon_sym_int] = ACTIONS(99),
    [anon_sym_float] = ACTIONS(99),
    [anon_sym_string] = ACTIONS(99),
    [anon_sym_bool] = ACTIONS(99),
    [anon_sym_thing] = ACTIONS(99),
    [anon_sym_error] = ACTIONS(99),
    [anon_sym_DOT] = ACTIONS(95),
    [sym_number] = ACTIONS(97),
    [sym_string] = ACTIONS(97),
    [anon_sym_yes] = ACTIONS(99),
    [anon_sym_no] = ACTIONS(99),
    [sym_nil] = ACTIONS(99),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_identifier] = ACTIONS(103),
    [anon_sym_struct] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_fun] = ACTIONS(103),
    [anon_sym_egg] = ACTIONS(103),
    [anon_sym_rock] = ACTIONS(103),
    [anon_sym_enum] = ACTIONS(103),
    [anon_sym_map] = ACTIONS(103),
    [anon_sym_type] = ACTIONS(103),
    [anon_sym_ayla] = ACTIONS(103),
    [anon_sym_elen] = ACTIONS(103),
    [anon_sym_four] = ACTIONS(103),
    [anon_sym_why] = ACTIONS(103),
    [anon_sym_back] = ACTIONS(103),
    [anon_sym_kitkat] = ACTIONS(103),
    [anon_sym_next] = ACTIONS(103),
    [anon_sym_decide] = ACTIONS(103),
    [anon_sym_when] = ACTIONS(103),
    [anon_sym_otherwise] = ACTIONS(103),
    [anon_sym_spawn] = ACTIONS(103),
    [anon_sym_with] = ACTIONS(103),
    [anon_sym_it] = ACTIONS(103),
    [anon_sym_in] = ACTIONS(103),
    [anon_sym_range] = ACTIONS(103),
    [anon_sym_int] = ACTIONS(103),
    [anon_sym_float] = ACTIONS(103),
    [anon_sym_string] = ACTIONS(103),
    [anon_sym_bool] = ACTIONS(103),
    [anon_sym_thing] = ACTIONS(103),
    [anon_sym_error] = ACTIONS(103),
    [sym_number] = ACTIONS(101),
    [sym_string] = ACTIONS(101),
    [anon_sym_yes] = ACTIONS(103),
    [anon_sym_no] = ACTIONS(103),
    [sym_nil] = ACTIONS(103),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_identifier] = ACTIONS(107),
    [anon_sym_struct] = ACTIONS(107),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_fun] = ACTIONS(107),
    [anon_sym_egg] = ACTIONS(107),
    [anon_sym_rock] = ACTIONS(107),
    [anon_sym_enum] = ACTIONS(107),
    [anon_sym_map] = ACTIONS(107),
    [anon_sym_type] = ACTIONS(107),
    [anon_sym_ayla] = ACTIONS(107),
    [anon_sym_elen] = ACTIONS(107),
    [anon_sym_four] = ACTIONS(107),
    [anon_sym_why] = ACTIONS(107),
    [anon_sym_back] = ACTIONS(107),
    [anon_sym_kitkat] = ACTIONS(107),
    [anon_sym_next] = ACTIONS(107),
    [anon_sym_decide] = ACTIONS(107),
    [anon_sym_when] = ACTIONS(107),
    [anon_sym_otherwise] = ACTIONS(107),
    [anon_sym_spawn] = ACTIONS(107),
    [anon_sym_with] = ACTIONS(107),
    [anon_sym_it] = ACTIONS(107),
    [anon_sym_in] = ACTIONS(107),
    [anon_sym_range] = ACTIONS(107),
    [anon_sym_int] = ACTIONS(107),
    [anon_sym_float] = ACTIONS(107),
    [anon_sym_string] = ACTIONS(107),
    [anon_sym_bool] = ACTIONS(107),
    [anon_sym_thing] = ACTIONS(107),
    [anon_sym_error] = ACTIONS(107),
    [sym_number] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [anon_sym_yes] = ACTIONS(107),
    [anon_sym_no] = ACTIONS(107),
    [sym_nil] = ACTIONS(107),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_struct] = ACTIONS(111),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_fun] = ACTIONS(111),
    [anon_sym_egg] = ACTIONS(111),
    [anon_sym_rock] = ACTIONS(111),
    [anon_sym_enum] = ACTIONS(111),
    [anon_sym_map] = ACTIONS(111),
    [anon_sym_type] = ACTIONS(111),
    [anon_sym_ayla] = ACTIONS(111),
    [anon_sym_elen] = ACTIONS(111),
    [anon_sym_four] = ACTIONS(111),
    [anon_sym_why] = ACTIONS(111),
    [anon_sym_back] = ACTIONS(111),
    [anon_sym_kitkat] = ACTIONS(111),
    [anon_sym_next] = ACTIONS(111),
    [anon_sym_decide] = ACTIONS(111),
    [anon_sym_when] = ACTIONS(111),
    [anon_sym_otherwise] = ACTIONS(111),
    [anon_sym_spawn] = ACTIONS(111),
    [anon_sym_with] = ACTIONS(111),
    [anon_sym_it] = ACTIONS(111),
    [anon_sym_in] = ACTIONS(111),
    [anon_sym_range] = ACTIONS(111),
    [anon_sym_int] = ACTIONS(111),
    [anon_sym_float] = ACTIONS(111),
    [anon_sym_string] = ACTIONS(111),
    [anon_sym_bool] = ACTIONS(111),
    [anon_sym_thing] = ACTIONS(111),
    [anon_sym_error] = ACTIONS(111),
    [sym_number] = ACTIONS(109),
    [sym_string] = ACTIONS(109),
    [anon_sym_yes] = ACTIONS(111),
    [anon_sym_no] = ACTIONS(111),
    [sym_nil] = ACTIONS(111),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(113),
    [sym_identifier] = ACTIONS(115),
    [anon_sym_struct] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(113),
    [anon_sym_fun] = ACTIONS(115),
    [anon_sym_egg] = ACTIONS(115),
    [anon_sym_rock] = ACTIONS(115),
    [anon_sym_enum] = ACTIONS(115),
    [anon_sym_map] = ACTIONS(115),
    [anon_sym_type] = ACTIONS(115),
    [anon_sym_ayla] = ACTIONS(115),
    [anon_sym_elen] = ACTIONS(115),
    [anon_sym_four] = ACTIONS(115),
    [anon_sym_why] = ACTIONS(115),
    [anon_sym_back] = ACTIONS(115),
    [anon_sym_kitkat] = ACTIONS(115),
    [anon_sym_next] = ACTIONS(115),
    [anon_sym_decide] = ACTIONS(115),
    [anon_sym_when] = ACTIONS(115),
    [anon_sym_otherwise] = ACTIONS(115),
    [anon_sym_spawn] = ACTIONS(115),
    [anon_sym_with] = ACTIONS(115),
    [anon_sym_it] = ACTIONS(115),
    [anon_sym_in] = ACTIONS(115),
    [anon_sym_range] = ACTIONS(115),
    [anon_sym_int] = ACTIONS(115),
    [anon_sym_float] = ACTIONS(115),
    [anon_sym_string] = ACTIONS(115),
    [anon_sym_bool] = ACTIONS(115),
    [anon_sym_thing] = ACTIONS(115),
    [anon_sym_error] = ACTIONS(115),
    [sym_number] = ACTIONS(113),
    [sym_string] = ACTIONS(113),
    [anon_sym_yes] = ACTIONS(115),
    [anon_sym_no] = ACTIONS(115),
    [sym_nil] = ACTIONS(115),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(117),
    [sym_identifier] = ACTIONS(119),
    [anon_sym_struct] = ACTIONS(119),
    [anon_sym_RBRACE] = ACTIONS(117),
    [anon_sym_fun] = ACTIONS(119),
    [anon_sym_egg] = ACTIONS(119),
    [anon_sym_rock] = ACTIONS(119),
    [anon_sym_enum] = ACTIONS(119),
    [anon_sym_map] = ACTIONS(119),
    [anon_sym_type] = ACTIONS(119),
    [anon_sym_ayla] = ACTIONS(119),
    [anon_sym_elen] = ACTIONS(119),
    [anon_sym_four] = ACTIONS(119),
    [anon_sym_why] = ACTIONS(119),
    [anon_sym_back] = ACTIONS(119),
    [anon_sym_kitkat] = ACTIONS(119),
    [anon_sym_next] = ACTIONS(119),
    [anon_sym_decide] = ACTIONS(119),
    [anon_sym_when] = ACTIONS(119),
    [anon_sym_otherwise] = ACTIONS(119),
    [anon_sym_spawn] = ACTIONS(119),
    [anon_sym_with] = ACTIONS(119),
    [anon_sym_it] = ACTIONS(119),
    [anon_sym_in] = ACTIONS(119),
    [anon_sym_range] = ACTIONS(119),
    [anon_sym_int] = ACTIONS(119),
    [anon_sym_float] = ACTIONS(119),
    [anon_sym_string] = ACTIONS(119),
    [anon_sym_bool] = ACTIONS(119),
    [anon_sym_thing] = ACTIONS(119),
    [anon_sym_error] = ACTIONS(119),
    [sym_number] = ACTIONS(117),
    [sym_string] = ACTIONS(117),
    [anon_sym_yes] = ACTIONS(119),
    [anon_sym_no] = ACTIONS(119),
    [sym_nil] = ACTIONS(119),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(25)] = {
    [ts_builtin_sym_end] = ACTIONS(121),
    [sym_identifier] = ACTIONS(123),
    [anon_sym_struct] = ACTIONS(123),
    [anon_sym_RBRACE] = ACTIONS(121),
    [anon_sym_fun] = ACTIONS(123),
    [anon_sym_egg] = ACTIONS(123),
    [anon_sym_rock] = ACTIONS(123),
    [anon_sym_enum] = ACTIONS(123),
    [anon_sym_map] = ACTIONS(123),
    [anon_sym_type] = ACTIONS(123),
    [anon_sym_ayla] = ACTIONS(123),
    [anon_sym_elen] = ACTIONS(123),
    [anon_sym_four] = ACTIONS(123),
    [anon_sym_why] = ACTIONS(123),
    [anon_sym_back] = ACTIONS(123),
    [anon_sym_kitkat] = ACTIONS(123),
    [anon_sym_next] = ACTIONS(123),
    [anon_sym_decide] = ACTIONS(123),
    [anon_sym_when] = ACTIONS(123),
    [anon_sym_otherwise] = ACTIONS(123),
    [anon_sym_spawn] = ACTIONS(123),
    [anon_sym_with] = ACTIONS(123),
    [anon_sym_it] = ACTIONS(123),
    [anon_sym_in] = ACTIONS(123),
    [anon_sym_range] = ACTIONS(123),
    [anon_sym_int] = ACTIONS(123),
    [anon_sym_float] = ACTIONS(123),
    [anon_sym_string] = ACTIONS(123),
    [anon_sym_bool] = ACTIONS(123),
    [anon_sym_thing] = ACTIONS(123),
    [anon_sym_error] = ACTIONS(123),
    [sym_number] = ACTIONS(121),
    [sym_string] = ACTIONS(121),
    [anon_sym_yes] = ACTIONS(123),
    [anon_sym_no] = ACTIONS(123),
    [sym_nil] = ACTIONS(123),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_type_identifier,
    STATE(40), 1,
      sym_primitive_type,
    ACTIONS(125), 6,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_bool,
      anon_sym_thing,
      anon_sym_error,
  [18] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [32] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [46] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_argument_list_repeat1,
  [62] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [76] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      sym_parameter_list,
  [89] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
  [102] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_argument_list_repeat1,
  [115] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [126] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_argument_list_repeat1,
  [139] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_parameter_list_repeat1,
  [152] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
  [165] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
  [175] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block,
  [185] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
  [208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_identifier,
  [215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
  [222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
  [229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_identifier,
  [236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_type_identifier,
  [243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
  [250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(26)] = 0,
  [SMALL_STATE(27)] = 18,
  [SMALL_STATE(28)] = 32,
  [SMALL_STATE(29)] = 46,
  [SMALL_STATE(30)] = 62,
  [SMALL_STATE(31)] = 76,
  [SMALL_STATE(32)] = 89,
  [SMALL_STATE(33)] = 102,
  [SMALL_STATE(34)] = 115,
  [SMALL_STATE(35)] = 126,
  [SMALL_STATE(36)] = 139,
  [SMALL_STATE(37)] = 152,
  [SMALL_STATE(38)] = 165,
  [SMALL_STATE(39)] = 175,
  [SMALL_STATE(40)] = 185,
  [SMALL_STATE(41)] = 193,
  [SMALL_STATE(42)] = 201,
  [SMALL_STATE(43)] = 208,
  [SMALL_STATE(44)] = 215,
  [SMALL_STATE(45)] = 222,
  [SMALL_STATE(46)] = 229,
  [SMALL_STATE(47)] = 236,
  [SMALL_STATE(48)] = 243,
  [SMALL_STATE(49)] = 250,
  [SMALL_STATE(50)] = 257,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 5, 0, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 5, 0, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 4, 0, 4),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_decl, 4, 0, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_decl, 5, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 6, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 2, 0, 5),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ayla(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
